//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeClothe
    {
        public int IdTypeCloth { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.Guid> Createdby { get; set; }
        public Nullable<System.Guid> Updatedby { get; set; }
        public Nullable<System.DateTime> Updateddate { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public string NameofType { get; set; }
    }
}
